UckgiDuckgi/PayAll-BE

build.gradle
src/main/java/com/example/PayAll_BE/config/RedisConfig.java
src/main/java/com/example/PayAll_BE/controller/AuthController.java
src/main/java/com/example/PayAll_BE/dto/AuthRequestDto.java
src/main/java/com/example/PayAll_BE/dto/AuthResponseDto.java
src/main/java/com/example/PayAll_BE/dto/RegisterRequestDto.java
src/main/java/com/example/PayAll_BE/entity/User.java
src/main/java/com/example/PayAll_BE/repository/UserRepository.java
src/main/java/com/example/PayAll_BE/service/AuthService.java
src/main/java/com/example/PayAll_BE/service/JwtService.java
src/main/java/com/example/PayAll_BE/service/RedisService.java

Login ,회원가입

---

src/main/java/com/example/PayAll_BE/controller/LimitController.java
src/main/java/com/example/PayAll_BE/controller/StatisticsController.java
src/main/java/com/example/PayAll_BE/dto/Limit/LimitRequestDto.java
src/main/java/com/example/PayAll_BE/dto/Limit/LimitResponseDto.java
src/main/java/com/example/PayAll_BE/dto/Statistics/StatisticsDetailResponseDto.java
src/main/java/com/example/PayAll_BE/dto/Statistics/StatisticsResponseDto.java
src/main/java/com/example/PayAll_BE/entity/Limit.java
src/main/java/com/example/PayAll_BE/entity/Statistics.java
src/main/java/com/example/PayAll_BE/entity/enums/StatisticsCategory.java
src/main/java/com/example/PayAll_BE/repository/LimitRepository.java
src/main/java/com/example/PayAll_BE/repository/PaymentRepository.java
src/main/java/com/example/PayAll_BE/repository/StatisticsRepository.java
src/main/java/com/example/PayAll_BE/service/LimitService.java
src/main/java/com/example/PayAll_BE/service/StatisticsService.java

- 소비 분석 카테고리 ENUM 추가
- 소비 분석 & 소비 목표 엔티티 추가
- 소비 분석 조회 API 구현
- 소비 분석 카테고리별 상세 조회 API 구현
- 소비 목표 등록 API 구현
- 소비 목표 조회 API 구현

[feat] 🐯 엔티티 구현 & 소비 분석 API 구현 & 소비 목표 API 구현

---

src/main/java/com/example/PayAll_BE/controller/CartController.java
src/main/java/com/example/PayAll_BE/controller/RecommendController.java
src/main/java/com/example/PayAll_BE/dto/Cart/CartRequestDto.java
src/main/java/com/example/PayAll_BE/dto/RecommendProductDto.java
src/main/java/com/example/PayAll_BE/entity/PaymentDetail.java
src/main/java/com/example/PayAll_BE/product/ProductApiClient.java
src/main/java/com/example/PayAll_BE/repository/PaymentDetailRepository.java
src/main/java/com/example/PayAll_BE/repository/PaymentRepository.java
src/main/java/com/example/PayAll_BE/service/CartService.java
src/main/java/com/example/PayAll_BE/service/JwtService.java
src/main/java/com/example/PayAll_BE/service/RecommendService.java

-  최근 지출 품목 최저가 추천 api 
- 장바구니 api에 jwt 토큰 기반으로 수정

[fix] 🧸 최근 지출 품목 최저가 추천 api 로직 수정

---

src/main/java/com/example/PayAll_BE/controller/LimitController.java
src/main/java/com/example/PayAll_BE/dto/Limit/LimitRegisterRequestDto.java
src/main/java/com/example/PayAll_BE/dto/Limit/LimitRegisterResponseDto.java
src/main/java/com/example/PayAll_BE/dto/Limit/LimitResponseDto.java
src/main/java/com/example/PayAll_BE/dto/Statistics/StatisticsResponseDto.java
src/main/java/com/example/PayAll_BE/entity/Limits.java
src/main/java/com/example/PayAll_BE/repository/LimitRepository.java
src/main/java/com/example/PayAll_BE/service/LimitService.java

- 소비 목표 등록 API
- 소비 목표 조회 API
- Limit 엔티티명 -> Limits 로 변경

[feat] 🐯 소비 목표 등록 & 소비 목표 조회 API 수정

---

src/main/java/com/example/PayAll_BE/controller/ProductController.java
src/main/java/com/example/PayAll_BE/controller/RecommendationController.java
src/main/java/com/example/PayAll_BE/dto/ProductResponseDto.java
src/main/java/com/example/PayAll_BE/dto/RecommendationResponseDto.java
src/main/java/com/example/PayAll_BE/dto/StoreStatisticsDto.java
src/main/java/com/example/PayAll_BE/entity/Benefit.java
src/main/java/com/example/PayAll_BE/entity/Product.java
src/main/java/com/example/PayAll_BE/entity/Recommendation.java
src/main/java/com/example/PayAll_BE/entity/enums/ProductType.java
src/main/java/com/example/PayAll_BE/repository/BenefitRepository.java
src/main/java/com/example/PayAll_BE/repository/PaymentRepository.java
src/main/java/com/example/PayAll_BE/repository/RecommendationRepository.java
src/main/java/com/example/PayAll_BE/service/RecommendationService.java

🐿️ Feature/mydata

---

src/main/java/com/example/PayAll_BE/controller/StatisticsController.java
src/main/java/com/example/PayAll_BE/controller/UserController.java
src/main/java/com/example/PayAll_BE/repository/PaymentRepository.java
src/main/java/com/example/PayAll_BE/service/StatisticsService.java
src/main/java/com/example/PayAll_BE/service/UserService.java

[feat] 🐯 소비 분석 카테고리별 상세 조회 API 구현

[feat] 🐯 소비 분석 카테고리별 상세 조회 API 구현

---

src/main/java/com/example/PayAll_BE/config/security/SecurityConfig.java

"/auth/sign-in","/auth/sign-up",

[fix] 🐿 시큐리티 경로 추가

---

src/main/java/com/example/PayAll_BE/controller/AuthController.java
src/main/java/com/example/PayAll_BE/controller/LimitController.java
src/main/java/com/example/PayAll_BE/controller/StatisticsController.java
src/main/java/com/example/PayAll_BE/controller/UserController.java
src/main/java/com/example/PayAll_BE/dto/AuthResponseDto.java
src/main/java/com/example/PayAll_BE/entity/User.java
src/main/java/com/example/PayAll_BE/service/AuthService.java

- Permission 검증 추가
- User / Limits / Statistics 컨트롤러 수정

[Feat] 🐯 Permission 추가 & 컨트롤러 수정

---

src/main/java/com/example/PayAll_BE/controller/AuthController.java
src/main/java/com/example/PayAll_BE/dto/PlatformResponseDto.java
src/main/java/com/example/PayAll_BE/service/AuthService.java

- 외부 플랫폼 등록  api 구현
- 외부 플랫폼 조회 api 구현

[feat] 🧸 외부 플랫폼 등록 및 조회 api 구현

---

src/main/java/com/example/PayAll_BE/repository/PaymentRepository.java
src/main/java/com/example/PayAll_BE/service/LimitService.java

소비 목표 조회 API에 구현 안했던 로직인 
1. 이번 달 시작 ~ 현재  날짜까지 소비 금액 계산 및 조회
2. 절약금액 계산
추가했습니다

[feat] 🐯 잊고있던 소비 목표 조회 API - 현재날짜까지 소비금액 조회 & 절약금액 계산 로직 추가

---

src/main/java/com/example/PayAll_BE/dto/Cart/CartRequestDto.java
src/main/java/com/example/PayAll_BE/mydata/service/MydataService.java
src/main/java/com/example/PayAll_BE/service/AuthService.java
src/main/java/com/example/PayAll_BE/service/CartService.java
src/main/java/com/example/PayAll_BE/service/JwtService.java

- 장바구니 추가 request dto 수정
- 마이데이터 연동 시점 수정

[fix] 🧸 장바구니 추가 request dto 수정

---

src/main/java/com/example/PayAll_BE/dto/Limit/LimitResponseDto.java
src/main/java/com/example/PayAll_BE/dto/Statistics/StatisticsResponseDto.java
src/main/java/com/example/PayAll_BE/entity/enums/Category.java
src/main/java/com/example/PayAll_BE/service/LimitService.java
src/main/java/com/example/PayAll_BE/service/StatisticsService.java

- 소비 목표 조회 API 로직 수정
- Category enum 수정
- Statistics  Service 코드 수정

[fix] 🐯 소비 목표 조회 api 로직 수정 및 기타 수정

---

build.gradle
src/main/java/com/example/PayAll_BE/customer/account/AccountController.java
src/main/java/com/example/PayAll_BE/customer/cart/CartController.java
src/main/java/com/example/PayAll_BE/customer/limit/LimitController.java
src/main/java/com/example/PayAll_BE/customer/limit/LimitService.java
src/main/java/com/example/PayAll_BE/customer/limit/dto/LimitResponseDto.java
src/main/java/com/example/PayAll_BE/customer/payment/PaymentController.java
src/main/java/com/example/PayAll_BE/customer/product/ProductController.java
src/main/java/com/example/PayAll_BE/customer/purchase/PurchaseController.java
src/main/java/com/example/PayAll_BE/customer/receipt/ReceiptController.java
src/main/java/com/example/PayAll_BE/customer/recommendation/RecommendationController.java
src/main/java/com/example/PayAll_BE/customer/search/SearchController.java
src/main/java/com/example/PayAll_BE/customer/statistics/StatisticsController.java
src/main/java/com/example/PayAll_BE/customer/user/UserController.java
src/main/java/com/example/PayAll_BE/global/auth/controller/AuthController.java
src/main/java/com/example/PayAll_BE/global/config/SwaggerConfig.java
src/main/java/com/example/PayAll_BE/global/config/security/JwtAuthenticationFilter.java
src/main/java/com/example/PayAll_BE/global/config/security/SecurityConfig.java
src/main/java/com/example/PayAll_BE/global/mydata/controller/MydataController.java

[feat] 🐯 스웨거 설정 및 작성

---

src/main/java/com/example/PayAll_BE/customer/cart/CartController.java
src/main/java/com/example/PayAll_BE/customer/cart/CartRepository.java
src/main/java/com/example/PayAll_BE/customer/cart/CartService.java
src/main/java/com/example/PayAll_BE/customer/cart/dto/CartMapper.java
src/main/java/com/example/PayAll_BE/customer/cart/dto/CartRequestDto.java
src/main/java/com/example/PayAll_BE/customer/purchase/PurchaseService.java
src/main/java/com/example/PayAll_BE/customer/search/SearchService.java
src/main/java/com/example/PayAll_BE/global/auth/dto/PlatformResponseDto.java
src/main/java/com/example/PayAll_BE/global/auth/service/AuthService.java
src/main/java/com/example/PayAll_BE/global/crawlingProduct/CrawlingProductApiClient.java

- 장바구니 추가 로직 수정
- 검색 상품 redis 저장 구현
- 외부 플랫폼 조회 시 response dto 수정

[fix] 🧸 장바구니 추가 로직 수정

---

src/main/java/com/example/PayAll_BE/customer/limit/LimitController.java
src/main/java/com/example/PayAll_BE/customer/limit/LimitService.java

[fix] 🐯 소비 목표 조회 API : 로직 수정

---

src/main/resources/temp.txt
src/test/java/com/example/PayAll_BE/customer/limit/LimitControllerTest.java
src/test/java/com/example/PayAll_BE/customer/payment/PaymentControllerTest.java

[feat] 🏀 CI/CD 파이프라인 구축

---

.github/workfllows/cicd.yml

[fix] 🏀 CI/CD파이프라인 수정

---

src/main/java/com/example/PayAll_BE/global/config/security/SecurityConfig.java

[chore] 🐿 cors 서버 도메인으로 수정

---

src/main/java/com/example/PayAll_BE/global/config/security/SecurityConfig.java

[[fix] 🐿 cors 서버 mockIp 추가](https://github.com/UckgiDuckgi/PayAll-BE/commit/525f49ca00d2f44cd7146089e86af8e955af6234)

[fix] 🐿 cors 서버 mockIp 추가

---

src/main/java/com/example/PayAll_BE/customer/benefit/Benefit.java
src/main/java/com/example/PayAll_BE/customer/store/Store.java

[fix] 🧸 store, beneift 엔티티 수정

---

build.gradle
src/main/java/com/example/PayAll_BE/customer/payment/PaymentController.java
src/main/java/com/example/PayAll_BE/customer/payment/PaymentRepository.java
src/main/java/com/example/PayAll_BE/customer/payment/PaymentService.java
src/main/java/com/example/PayAll_BE/customer/paymentDetails/PaymentDetailRepository.java
src/main/java/com/example/PayAll_BE/customer/paymentDetails/dto/PaymentListRequestDto.java
src/main/java/com/example/PayAll_BE/global/config/monitoring/CustomHealthIndicator.java
src/main/java/com/example/PayAll_BE/global/config/monitoring/CustomInfoContributor.java
src/main/java/com/example/PayAll_BE/global/config/security/SecurityConfig.java
src/main/java/com/example/PayAll_BE/global/crawlingProduct/CrawlingProductDto.java
src/test/java/com/example/PayAll_BE/customer/limit/LimitControllerTest.java
src/test/java/com/example/PayAll_BE/customer/payment/PaymentControllerTest.java
src/test/java/com/example/PayAll_BE/customer/product/ProductControllerTest.java
src/test/java/com/example/PayAll_BE/customer/receipt/ReceiptControllerTest.java
src/test/java/com/example/PayAll_BE/global/auth/AuthControllerTest.java

PaymentControllerTest 디테일업로드 부분 아직 작성중

[test] 🌱 테스트코드 작성 및 actuator, jacoco 세팅 && PaymentList pageable 삭제 && paymentDetail 업로드 부분 로직 추가
